apiVersion: "nais.io/v1alpha1"
kind: "Alert"
metadata:
  name: kontakt-oss-api-alert
  labels:
    team: arbeidsgiver
spec:
  receivers:
    slack:
      channel: '#arbeidsgiver-teamia-utvikling'
      prependText: '<!here> | '
  alerts:
    - alert: applikasjon nede
      expr: sum(up{app="kontakt-oss-api", job="kubernetes-pods"}) == 0
      for: 2m
      description: "{{ $labels.app }} er nede i {{ $labels.kubernetes_namespace }}"
      action: "`kubectl describe pod {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for logger"

    - alert: det har skjedd en feil i kontakt-oss-api
        expr: sum(increase(logd_messages_total{log_app="kontakt-oss-api",log_level="Error"}[3m])) by (log_app,log_pod_name) > 0
        for: 30s
        description: "{{ $labels.log_app }} har logget en feil"
        action: "`kubectl describe pod {{ $labels.log_pod_name }}` for events, og `kubectl logs {{ $labels.log_pod_name }}` for logger"
