apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tag-kontaktskjema
  namespace: default
  labels:
    team: teamtag
spec:
  image: navikt/tag-kontaktskjema:latest
  team: teamtag
  port: 8080
  secrets: true
  ingresses:
    - https://arbeidsgiver.nav.no/kontaktskjema
    - https://tag-kontaktskjema.nais.oera.no
  liveness:
    path: /kontaktskjema/internal/actuator/info
    initialDelay: 40
  readiness:
    path: /kontaktskjema/internal/actuator/info
    initialDelay: 40
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
prometheus:
  enabled: true
  path: /kontaktskjema/internal/actuator/prometheus
