# kontakt-oss
kontakt-oss:
  kafka:
    enabled: false
  fylke-scheduler:
    enabled: false
  utsending-scheduler:
    enabled: false

norg:
  url: https://app-q0.adeo.no/norg2/api/v1
kodeverk:
  url: https://kodeverk.nais.preprod.local/api/v1
unleash:
  url: https://unleash.nais.io/api/
  profile: dev

salesforce:
  auth:
    url: https://test.salesforce.com/services/oauth2/token
  contactform:
    url: https://navdialog--preprod.my.salesforce.com/services/apexrest/ContactForm

database:
  url: "jdbc:postgresql://${NAIS_DATABASE_KONTAKT-OSS-API_KONTAKT-OSS-DEV_HOST}:${NAIS_DATABASE_KONTAKT-OSS-API_KONTAKT-OSS-DEV_PORT}/${NAIS_DATABASE_KONTAKT-OSS-API_KONTAKT-OSS-DEV_DATABASE}"
  username: ${NAIS_DATABASE_KONTAKT-OSS-API_KONTAKT-OSS-DEV_USERNAME}
  password: ${NAIS_DATABASE_KONTAKT-OSS-API_KONTAKT-OSS-DEV_PASSWORD}

kontaktskjema:
  max-requests-per-10-min: 10