# kontakt-oss
kontakt-oss:
  kafka:
    enabled: true

norg:
  url: https://app-q0.adeo.no/norg2/api/v1
kodeverk:
  url: https://kodeverk.nais.preprod.local/api/v1
unleash:
  url: https://unleash.nais.io/api/
  profile: dev

salesforce:
  auth:
    url: https://test.salesforce.com/services/oauth2/token
  contactform:
    url: https://navdialog--preprod.my.salesforce.com/services/apexrest/ContactForm

database:
  navn: kontakt-oss-preprod
vault:
  mount-path: postgresql/preprod-fss

kontaktskjema:
  max-requests-per-10-min: 10