# kontakt-oss
kontakt-oss:
  kafka:
    enabled: false
  fylke-scheduler:
    enabled: true
  utsending-scheduler:
    enabled: true

ssb:
  fixed-rate: 86400000  # Hver dag i millisekunder: 1000 * 1440 * 60 = 86,400,000

unleash:
  url: https://unleash.nais.io/api/
  profile: dev


database:
  url: "jdbc:postgresql://${NAIS_DATABASE_KONTAKT-OSS-API_KONTAKT-OSS-DEV_HOST}:${NAIS_DATABASE_KONTAKT-OSS-API_KONTAKT-OSS-DEV_PORT}/${NAIS_DATABASE_KONTAKT-OSS-API_KONTAKT-OSS-DEV_DATABASE}"
  username: ${NAIS_DATABASE_KONTAKT-OSS-API_KONTAKT-OSS-DEV_USERNAME}
  password: ${NAIS_DATABASE_KONTAKT-OSS-API_KONTAKT-OSS-DEV_PASSWORD}

kontaktskjema:
  max-requests-per-10-min: 10