spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      security.protocol: SSL
      ssl:
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore:
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: "kontakt-oss"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# kontakt-oss
kontakt-oss:
  kafka:
    config:
      bootstrap-servers: ${KAFKA_BROKERS}
      truststore-path: ${KAFKA_TRUSTSTORE_PATH}
      truststore-password: ${KAFKA_CREDSTORE_PASSWORD}
      keystore-path: ${KAFKA_KEYSTORE_PATH}
      keystore-password: ${KAFKA_CREDSTORE_PASSWORD}
      security-protocol: SSL
    enabled: false
    test-instance:
      enabled: false


server:
  servlet:
    context-path: /kontakt-oss-api

management:
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: /internal/actuator

norg:
  fixed-rate: 3600000 # Hver time i millisekunder: 1000 * 60 * 60 = 3600000

norg.url: https://app.adeo.no/norg2/api/v1
kodeverk.url: https://kodeverk.nais.adeo.no/api/v1
unleash:
  url: https://unleash.nais.io/api/
  profile: prod

kontaktskjema:
  max-requests-per-10-min: 10


salesforce:
  auth.url: https://login.salesforce.com/services/oauth2/token
  contactform.url: https://navdialog.my.salesforce.com/services/apexrest/ContactForm

database.navn: kontakt-oss-prod
vault.mount-path: postgresql/prod-fss
