server.servlet.context-path: /kontakt-oss-api

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: ${CONTROLLER_BASEPATH:/kontakt-oss-api}/internal/actuator

norg.fixed-rate: 3600000 # Hver time i millisekunder: 1000 * 60 * 60 = 3600000

---
spring:
  profiles: dev
  h2.console:
    enabled: true
    path: /h2

server.servlet.context-path: ""

mock.port: 8081

gsak.url: http://localhost:${mock.port}/gsak
norg.url: http://localhost:${mock.port}/norg

ENABLE_GSAK: true

---
spring:
  profiles: preprod
gsak.url: https://oppgave.nais.preprod.local/api/v1/oppgaver
norg.url: https://app-q0.adeo.no/norg2/api/v1

---
spring:
  profiles: prod
gsak.url: https://oppgave.nais.adeo.no/api/v1/oppgaver
norg.url: https://app.adeo.no/norg2/api/v1
