spring:
  profiles.active: dev
  h2.console:
    enabled: false
    path: /h2

controller.basepath: ${CONTROLLER_BASEPATH:/kontaktskjema}

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: ${CONTROLLER_BASEPATH:/kontakt-oss-api}/internal/actuator
