server.servlet.context-path: /kontakt-oss-api

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: /internal/actuator

norg.fixed-rate: 3600000 # Hver time i millisekunder: 1000 * 60 * 60 = 3600000

spring.profiles.active: dev

kontaktskjema:
  max-requests-per-10-min: 1000

---
spring:
  profiles: dev
  h2.console:
    enabled: true
    path: /h2

mock:
  enabled: true
  port: 8081
  baseUrl: http://localhost:${mock.port}${server.servlet.context-path}

gsak.url: ${mock.baseUrl}/gsak
norg.url: ${mock.baseUrl}/norg
kodeverk.url: ${mock.baseUrl}/kodeverk

# Miljøvariabel som ellers settes i nais.yaml
ENABLE_GSAK: true

---

spring:
  profiles: kafka-test
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}

---
spring:
  profiles: preprod
  kafka:
    bootstrap-servers: b27apvl00045.preprod.local:8443, b27apvl00046.preprod.local:8443, b27apvl00047.preprod.local:8443
    client-id: kontakt-oss-api-preprod
    properties:
      security.protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${SERVICEBRUKER_NAVN}" password="${SERVICEBRUKER_PASSORD}";
      ssl.truststore:
        location: ${javax.net.ssl.trustStore}
        password: ${javax.net.ssl.trustStorePassword}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

gsak.url: https://oppgave.nais.preprod.local/api/v1/oppgaver
norg.url: https://app-q0.adeo.no/norg2/api/v1
kodeverk.url: https://kodeverk.nais.preprod.local/api/v1

database.navn: kontakt-oss-preprod
vault.mount-path: postgresql/preprod-fss

---
spring:
  profiles: prod
  kafka:
    bootstrap-servers: a01apvl00145.adeo.no:8443, a01apvl00146.adeo.no:8443, a01apvl00147.adeo.no:8443, a01apvl00148.adeo.no:8443, a01apvl00149.adeo.no:8443, a01apvl00150.adeo.no:8443
    client-id: kontakt-oss-api-prod
    properties:
      security.protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${SERVICEBRUKER_NAVN}" password="${SERVICEBRUKER_PASSORD}";
      ssl.truststore:
        location: ${javax.net.ssl.trustStore}
        password: ${javax.net.ssl.trustStorePassword}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

gsak.url: https://oppgave.nais.adeo.no/api/v1/oppgaver
norg.url: https://app.adeo.no/norg2/api/v1
kodeverk.url: https://kodeverk.nais.adeo.no/api/v1

kontaktskjema:
  max-requests-per-10-min: 10

database.navn: kontakt-oss-prod
vault.mount-path: postgresql/prod-fss
