server.servlet.context-path: /kontakt-oss-api

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: /internal/actuator

norg.fixed-rate: 3600000 # Hver time i millisekunder: 1000 * 60 * 60 = 3600000

spring.profiles.active: dev

kontaktskjema:
  max-requests-per-10-min: 1000

---
spring:
  profiles: dev
  h2.console:
    enabled: true
    path: /h2

#  kafka:
#    bootstrap-servers: b27apvl00045.preprod.local:8443, b27apvl00046.preprod.local:8443, b27apvl00047.preprod.local:8443
#    client-id: kontakt-oss-api-preprod
#    properties:
#      security.protocol: SASL_SSL
#      sasl:
#        mechanism: PLAIN
#        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${SERVICEBRUKER_NAVN}" password="${SERVICEBRUKER_PASSORD}";
#      ssl.truststore:
#        location: ${javax.net.ssl.trustStore}
#        password: ${javax.net.ssl.trustStorePassword}
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      group-id: kontakt-oss-api-preprod
#      max-poll-records: 1
#      auto-offset-reset: earliest
#      enable-auto-commit: false


mock:
  enabled: true
  port: 8081
  baseUrl: http://localhost:${mock.port}${server.servlet.context-path}

gsak.url: ${mock.baseUrl}/gsak
norg.url: ${mock.baseUrl}/norg
kodeverk.url: ${mock.baseUrl}/kodeverk

# Miljøvariabel som ellers settes i nais.yaml
ENABLE_GSAK: true

---
spring:
  profiles: preprod
  kafka:
    bootstrap-servers: b27apvl00045.preprod.local:8443, b27apvl00046.preprod.local:8443, b27apvl00047.preprod.local:8443
    client-id: kontakt-oss-api-preprod
    properties:
      security.protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${SERVICEBRUKER_NAVN}" password="${SERVICEBRUKER_PASSORD}";
      ssl.truststore:
        location: ${javax.net.ssl.trustStore}
        password: ${javax.net.ssl.trustStorePassword}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.JsonDeserializer
      group-id: kontakt-oss-api-preprod
      max-poll-records: 1
      auto-offset-reset: earliest
      enable-auto-commit: false

gsak.url: https://oppgave.nais.preprod.local/api/v1/oppgaver
norg.url: https://app-q0.adeo.no/norg2/api/v1
kodeverk.url: https://kodeverk.nais.preprod.local/api/v1

database.navn: kontakt-oss-preprod
vault.mount-path: postgresql/preprod-fss

---
spring:
  profiles: prod
gsak.url: https://oppgave.nais.adeo.no/api/v1/oppgaver
norg.url: https://app.adeo.no/norg2/api/v1
kodeverk.url: https://kodeverk.nais.adeo.no/api/v1

kontaktskjema:
  max-requests-per-10-min: 10

database.navn: kontakt-oss-prod
vault.mount-path: postgresql/prod-fss
