spring:
  profiles.active: local
  main.banner-mode: "off"

server.servlet.context-path: /kontakt-oss-api

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: /internal/actuator

norg.fixed-rate: 3600000 # Hver time i millisekunder: 1000 * 60 * 60 = 3600000

kontaktskjema:
  max-requests-per-10-min: 1000

---
spring:
  config.activate.on-profile: localpostgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

---
spring:
  config.activate.on-profile: local
  h2.console:
    enabled: true
    path: /h2

mock:
  enabled: true
  port: 8081
  baseUrl: http://localhost:${mock.port}${server.servlet.context-path}

norg.url: ${mock.baseUrl}/norg
kodeverk.url: ${mock.baseUrl}/kodeverk
unleash.url: http://unleash.herokuapp.com/api/

salesforce:
  auth.url: ${mock.baseUrl}/salesforce/auth
  contactform.url: ${mock.baseUrl}/salesforce/contactform
  username: user
  password: pass
  client:
    id: blabla
    secret: sdjhfg

nais.cluster.name: local


---
spring:
  config.activate.on-profile: dev

norg.url: https://app-q0.adeo.no/norg2/api/v1
kodeverk.url: https://kodeverk.nais.preprod.local/api/v1
unleash.url: https://unleash.nais.io/api/


salesforce:
  auth.url: https://test.salesforce.com/services/oauth2/token
  contactform.url: https://navdialog--preprod.my.salesforce.com/services/apexrest/ContactForm

database.navn: kontakt-oss-preprod
vault.mount-path: postgresql/preprod-fss

---
spring:
  config.activate.on-profile: prod

norg.url: https://app.adeo.no/norg2/api/v1
kodeverk.url: https://kodeverk.nais.adeo.no/api/v1
unleash.url: https://unleash.nais.io/api/

kontaktskjema:
  max-requests-per-10-min: 10

salesforce:
  auth.url: https://login.salesforce.com/services/oauth2/token
  contactform.url: https://navdialog.my.salesforce.com/services/apexrest/ContactForm

database.navn: kontakt-oss-prod
vault.mount-path: postgresql/prod-fss
