apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: kontakt-oss-api
  namespace: fager
  labels:
    team: fager
spec:
  image: {{version}}
  ingresses:
    - https://kontakt-oss-api.dev.nav.no/kontakt-oss-api/
  liveness:
    path: /kontakt-oss-api/internal/healthcheck
    initialDelay: 30
  readiness:
    path: /kontakt-oss-api/internal/healthcheck
    initialDelay: 30
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
  envFrom:
    - secret: kontakt-oss-api
  prometheus:
    enabled: true
    path: /kontakt-oss-api/internal/actuator/prometheus
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: kontaktskjema
            envVarPrefix: DB

  accessPolicy:
    outbound:
      external:
        - host: app-q0.adeo.no # norg2
        - host: kodeverk.nais.preprod.local
        - host: unleash.nais.io
        - host: test.salesforce.com
        - host: navdialog--preprod.my.salesforce.com

