apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: kontakt-oss-api
  namespace: team-innhold
  labels:
    team: team-innhold
spec:
  image: {{version}}
  port: 8080
  vault:
    enabled: true
  ingresses:
    - https://arbeidsgiver.nais.preprod.local/kontakt-oss-api/
  liveness:
    path: /kontakt-oss-api/internal/healthcheck
    initialDelay: 30
  readiness:
    path: /kontakt-oss-api/internal/healthcheck
    initialDelay: 30
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: FYLKESINNDELING_TVING_OPPDATERING
      value: "false"
  prometheus:
    enabled: true
    path: /kontakt-oss-api/internal/actuator/prometheus
  webproxy: true
  kafka:
    pool: nav-dev
