apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: kontakt-oss-api
  namespace: team-innhold
  labels:
    team: team-innhold
spec:
  image: {{version}}
  port: 8080
  vault:
    enabled: false
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: kontakt-oss-dev
  kafka:
    pool: nav-dev
  ingresses:
    - https://arbeidsgiver.dev.nav.no/kontakt-oss-api/
  liveness:
    path: /internal/isAlive
    initialDelay: 30
  readiness:
    path: /internal/isReady
    initialDelay: 30
  prometheus:
    enabled: true
    path: /kontakt-oss-api/internal/actuator/prometheus
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: FYLKESINNDELING_TVING_OPPDATERING
      value: "false"
  webproxy: true




