apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: arbeidsgiver-kontaktskjema
  namespace: team-innhold
  labels:
    team: team-innhold
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: -1
  acl:
    - team: team-innhold
      application: kontakt-oss-api
      access: readwrite
    - team: team-dialog
      application: sf-arbeidsgiver-kontaktskjema
      access: readwrite