apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: kontakt-oss-api
  namespace: default
  labels:
    team: arbeidsgiver
spec:
  image: {{version}}
  vault:
    enabled: true
  ingresses:
    - https://arbeidsgiver.nais.adeo.no/kontakt-oss-api/
  liveness:
    path: /kontakt-oss-api/internal/healthcheck
    initialDelay: 30
  readiness:
    path: /kontakt-oss-api/internal/healthcheck
    initialDelay: 30
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  prometheus:
    enabled: true
    path: /kontakt-oss-api/internal/actuator/prometheus
  webproxy: true
